/**
 * Typed contract client for Soroban contracts.
 *
 * Wraps `@stellar/stellar-sdk`'s `Spec` (which parses a contract's WASM
 * spec — the embedded list of function signatures, exported types, etc.)
 * and binds it to a `SorobanConnection` so every call goes through the
 * connection's simulate → prepare → sign → submit pipeline, with the
 * transaction preview flow and signature-request queueing intact.
 *
 * ## Why this exists
 *
 * Without a typed client, calling a Soroban contract requires building
 * `xdr.ScVal` args by hand — error-prone, especially for nested types
 * like `Map<Symbol, Vec<Address>>`. The SDK's `Spec.funcArgsToScVals()`
 * takes a native JS object and converts each field to the right ScVal
 * based on the function's spec entry, so `client.transfer({ from, to,
 * amount })` works instead of `contract.call('transfer', scvAddress(from),
 * scvAddress(to), scvI128(amount))`.
 *
 * This module adds a typed wrapper on top: the consumer provides a TS
 * interface describing the contract's methods, and gets back a client
 * whose methods are typed (autocomplete + type-checking on args and
 * return values). The interface is purely a compile-time artifact —
 * at runtime, args are converted via the spec, and the connection does
 * the actual invoke.
 *
 * ## Spec acquisition
 *
 * The spec is typically generated by the Stellar CLI:
 *
 *   stellar contract bindings typescript \
 *     --contract-id C... \
 *     --output-dir ./packages/my-contract \
 *     --network testnet
 *
 * This produces a local npm package whose default export includes the
 * spec entries as base64 strings. Pass `specEntries` (the array of
 * base64 strings or parsed `xdr.ScSpecEntry[]`) to `connection.contract()`
 * and you're done.
 *
 * For contracts whose spec you can't generate locally (e.g. someone
 * else's contract on mainnet), you can fetch the spec at runtime via
 * `rpc.getContractSpec(contractId)` (new in stellar-sdk v13+) — pass
 * the resulting entries to `connection.contract()`.
 */

import type { SorobanConnection } from './soroban.js';
import type { InvokeOptions, InvokeResult } from './soroban.js';

// Lazy SDK imports so this module doesn't force a specific stellar-sdk
// version on apps that only use the wallet layer.
type StellarSdkModule = typeof import('@stellar/stellar-sdk');
type SpecModule = typeof import('@stellar/stellar-sdk/contract');

/**
 * A function on the contract spec. The consumer's TS interface should
 * declare each method as `(args: {...}) => Promise<ReturnValue>` —
 * this type is the bridge that lets us typecheck the binding.
 *
 * The `args` object's keys MUST match the parameter names in the
 * contract's spec (stellar-sdk's `Spec.funcArgsToScVals` looks them
 * up by name). The return type can be anything `scValToNative` can
 * produce — typically `number | bigint | string | boolean | null |
 * object | undefined`.
 */
export type ContractMethod<Args extends object = object, Return = unknown> =
  (args: Args) => Promise<Return>;

/**
 * Marker type for a contract spec — the consumer provides an interface
 * whose methods match this shape, and we use it only for compile-time
 * type-checking. At runtime, the actual calls go through `Spec`.
 */
export interface ContractSpec {
  [method: string]: ContractMethod<object, unknown>;
}

/**
 * A typed client for a Soroban contract. Methods are derived from the
 * consumer's TS interface (`T`), so `client.transfer({ from, to, amount })`
 * is fully typed — wrong arg names, missing fields, or wrong types are
 * caught at compile time.
 *
 * Each method delegates to `SorobanConnection.invoke()`, so it goes
 * through the same simulate → prepare → sign → submit → poll pipeline,
 * with the transaction preview flow and signature-request queueing
 * intact.
 *
 * For read-only calls (functions marked `view` in the contract spec),
 * pass `{ simulateOnly: true }` — the call skips signing/submission
 * and resolves to the simulated return value directly.
 */
export class ContractClient<T extends ContractSpec = ContractSpec> {
  private connection: SorobanConnection;
  private contractId: string;
  private spec!: InstanceType<SpecModule['Spec']>;
  private _sdk: StellarSdkModule | null = null;

  constructor(opts: {
    connection: SorobanConnection;
    contractId: string;
    /** The contract's spec entries — base64 strings or parsed xdr.ScSpecEntry[]. Get these from `stellar contract bindings typescript`. */
    specEntries: string[] | import('@stellar/stellar-sdk').xdr.ScSpecEntry[];
  }) {
    this.connection = opts.connection;
    this.contractId = opts.contractId;
    // Construct the Spec eagerly — it's lightweight (just parses XDR
    // strings into the in-memory entry objects) and we want any spec
    // errors to surface at construction time, not on the first call.
    // We import the Spec class lazily because it lives in
    // '@stellar/stellar-sdk/contract', a subpath that's only resolvable
    // if @stellar/stellar-sdk is installed.
    //
    // The async IIFE here is a bit awkward — we can't make the constructor
    // async, so we kick off the import and stash the promise. The first
    // method call awaits it. This means a malformed specEntries array
    // doesn't throw at construction time, only at first use — acceptable
    // trade-off for keeping the constructor synchronous.
    this._specPromise = (async () => {
      const { Spec } = await import('@stellar/stellar-sdk/contract');
      return new Spec(opts.specEntries);
    })();
    // Attach a no-op catch handler to prevent "UnhandledPromiseRejection"
    // warnings if the spec is malformed and the consumer never calls a
    // method (so getSpec() is never awaited). The actual error still
    // surfaces when getSpec() is awaited — this just prevents the
    // process-level unhandled rejection warning.
    this._specPromise.catch(() => {});
  }

  private _specPromise: Promise<InstanceType<SpecModule['Spec']>>;

  private async getSpec(): Promise<InstanceType<SpecModule['Spec']>> {
    this.spec = await this._specPromise;
    return this.spec;
  }

  /**
   * Calls a contract method by name, with native JS args. The args
   * object's keys MUST match the parameter names in the contract's
   * spec — `Spec.funcArgsToScVals` looks them up by name.
   *
   * This is the low-level escape hatch — prefer the typed methods on
   * the client (returned by `connection.contract<T>()`) which are
   * derived from your TS interface.
   */
  async call<K extends string & keyof T>(
    method: K,
    args: T[K] extends ContractMethod<infer A, unknown> ? A : never,
    opts?: { simulateOnly?: boolean; baseFee?: string }
  ): Promise<T[K] extends ContractMethod<object, infer R> ? R : unknown> {
    const spec = await this.getSpec();
    // Convert the native args object to ScVal[] using the spec — this
    // handles all the type coercion (Address → ScAddress, bigint → ScInt,
    // arrays → Vec, etc.) based on the function's declared parameter types.
    const scArgs = spec.funcArgsToScVals(method as string, args as object);

    // Delegate to the connection's invoke pipeline. The connection handles
    // simulate → prepare → sign → submit → poll, and runs the transaction
    // through the onPreviewTransaction hook before signing.
    const invokeOpts: InvokeOptions = {
      contractId: this.contractId,
      method: method as string,
      args: scArgs as unknown[],
      simulateOnly: opts?.simulateOnly,
      baseFee: opts?.baseFee,
    };

    const result: InvokeResult = await this.connection.invoke(invokeOpts);

    // If simulateOnly, the result.returnValue is the simulation's retval
    // (still a raw ScVal in the current implementation — see
    // SorobanConnection.decodeSimResult). Convert it to native using
    // the spec's declared return type for this function.
    if (result.status === 'SIMULATED' || result.status === 'SUCCESS') {
      if (result.returnValue !== undefined) {
        // funcResToNative accepts either an ScVal or a base64 string.
        // The connection's returnValue is currently the raw simulation
        // response (decodeSimResult is a passthrough) — if it's an ScVal,
        // pass it through; if it's a string, pass that.
        try {
          return spec.funcResToNative(
            method as string,
            result.returnValue as import('@stellar/stellar-sdk').xdr.ScVal | string
          ) as T[K] extends ContractMethod<object, infer R> ? R : unknown;
        } catch {
          // If the spec doesn't declare a return type for this function
          // (e.g. void functions), or the conversion fails, return the
          // raw value as a fallback.
          return result.returnValue as T[K] extends ContractMethod<object, infer R> ? R : unknown;
        }
      }
    }

    return undefined as T[K] extends ContractMethod<object, infer R> ? R : unknown;
  }

  /**
   * Simulates a call without signing or submitting — for read-only
   * functions (those marked `view` in the contract spec) or for
   * previewing a write before the user commits.
   *
   * Equivalent to `call(method, args, { simulateOnly: true })` but
   * more readable at the call site.
   */
  async simulate<K extends string & keyof T>(
    method: K,
    args: T[K] extends ContractMethod<infer A, unknown> ? A : never
  ): Promise<T[K] extends ContractMethod<object, infer R> ? R : unknown> {
    return this.call(method, args, { simulateOnly: true });
  }

  /**
   * Returns the underlying `Spec` instance from @stellar/stellar-sdk,
   * for advanced use cases (inspecting function signatures, building
   * custom transactions, etc.).
   */
  async getUnderlyingSpec(): Promise<InstanceType<SpecModule['Spec']>> {
    return this.getSpec();
  }

  /** The contract ID this client is bound to. */
  get id(): string {
    return this.contractId;
  }
}

/**
 * Type helper for declaring a contract spec interface. Purely cosmetic —
 * makes the consumer's code read more naturally:
 *
 *   import { defineContractSpec } from '@saganta/stellar-appkit';
 *
 *   interface TokenContract extends defineContractSpec<{
 *     transfer: (args: { from: string; to: string; amount: bigint }) => Promise<boolean>;
 *     balanceOf: (args: { id: string }) => Promise<bigint>;
 *   }> {}
 *
 *   const token = soroban.contract<TokenContract>('C...', { specEntries });
 *   await token.transfer({ from, to, amount });  // typed
 */
export type defineContractSpec<T extends ContractSpec> = T;
